name: Build

on:
  push:
    branches: [ new-model ]

  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk:
          - Pharo64-10
          - Pharo64-11
        tensorflow: [ 2.15.0 ]
    name: TF ${{ matrix.tensorflow }}+${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v4
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Install TensorFlow
        run: ./scripts/install-tensorflow.sh
        env:
          VERSION: ${{ matrix.tensorflow }}
      - name: Install Pharo Dependencies
        run: ./scripts/install-pharo-dependencies.sh
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBTENSORFLOW_PATH: /usr/local/lib/libtensorflow.so
        timeout-minutes: 20
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          name: ${{matrix.os}}-${{matrix.smalltalk}}
          token: ${{ secrets.CODECOV_TOKEN }}
